### ISSUE TITLE
Flake test: test_api_keys

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-ruby#402]
```
  1) Error:
API keys#test_api_keys:
NoMethodError: undefined method `<=' for {:maxHitsPerQuery=>42}:Hash
    /home/circleci/project/lib/algolia/responses/update_api_key_response.rb:26:in `wait'
    /home/circleci/project/lib/algolia/search_client.rb:336:in `update_api_key!'
    /home/circleci/project/test/algolia/integration/search_client_test.rb:224:in `test_api_keys'
```

**Comment by aseure** [comment]
@chloelbn I see you closed this one but have we found the root cause of this issue?
