### ISSUE TITLE
Unable to reindex locally

### ISSUE THREAD

**Issue by wee007** [algolia/algoliasearch-client-ruby#91]
Hi there

I'm using Algolia for the first time and trying to get reindexing to work locally but it's throwing the error below:

Algolia::AlgoliaError: API not initialized

```
2016-09-30T06:18:00.071Z 50262 TID-oxqk9ev1w WARN: {"class":"Search::SomeWorker","args":[2,false],"retry":5,"queue":"default","jid":"1519b78812e13d6df5fdb6a9","created_at":1475216280.067702,"enqueued_at":1475216280.067759,**"error_message":"API not initialized","error_class":"Algolia::AlgoliaError"**,"failed_at":1475216280.0707068,"retry_count":0}
**2016-09-30T06:18:00.071Z 50262 TID-oxqk9ev1w WARN: Algolia::AlgoliaError: API not initialized**
2016-09-30T06:18:00.071Z 50262 TID-oxqk9ev1w WARN: /Users/xxx/.rvm/gems/ruby-2.3.1@foro/gems/algoliasearch-1.11.0/lib/algolia/client.rb:657:in `client'
/Users/xxx/.rvm/gems/ruby-2.3.1@foro/gems/algoliasearch-1.11.0/lib/algolia/index.rb:11:in `initialize'
/Users/xxx/.rvm/gems/ruby-2.3.1@foro/gems/algoliasearch-rails-1.15.0/lib/algoliasearch-rails.rb:229:in `new'
/Users/xxx/.rvm/gems/ruby-2.3.1@foro/gems/algoliasearch-rails-1.15.0/lib/algoliasearch-rails.rb:229:in `initialize'
/Users/xxx/.rvm/gems/ruby-2.3.1@foro/gems/algoliasearch-rails-1.15.0/lib/algoliasearch-rails.rb:647:in `new'
/Users/xxx/.rvm/gems/ruby-2.3.1@foro/gems/algoliasearch-rails-1.15.0/lib/algoliasearch-rails.rb:647:in `algolia_ensure_init'
/Users/xxx/.rvm/gems/ruby-2.3.1@foro/gems/algoliasearch-rails-1.15.0/lib/algoliasearch-rails.rb:492:in `block in algolia_index!'
/Users/xxx/.rvm/gems/ruby-2.3.1@foro/gems/algoliasearch-rails-1.15.0/lib/algoliasearch-rails.rb:489:in `each'
/Users/xxx/.rvm/gems/ruby-2.3.1@foro/gems/algoliasearch-rails-1.15.0/lib/algoliasearch-rails.rb:489:in `algolia_index!'
/Users/xxx/.rvm/gems/ruby-2.3.1@foro/gems/algoliasearch-rails-1.15.0/lib/algoliasearch-rails.rb:792:in `algolia_index!'
```
I had no trouble connecting to the Algolia client as shown below:
```
[1] pry(main)> Algolia::Client.new(application_id: xxx, api_key: xxx)
=> #<Algolia::Client:0x007fe100329f40
 @api_key="xxx",
 @application_id="xxx",
 @batch_timeout=120,
 @connect_timeout=2,
 @headers=
  {"X-Algolia-API-Key"=>"xxx",
   "X-Algolia-Application-Id"=>"xxx",
   "Content-Type"=>"application/json; charset=utf-8",
   "User-Agent"=>"Algolia for Ruby 1.11.0"},
 @hosts=["xxx.algolia.net", "xxx-1.algolianet.com", "xxx-3.algolianet.com", "xxx-2.algolianet.com"],
 @receive_timeout=30,
 @search_hosts=["xxx-dsn.algolia.net", "xxx-2.algolianet.com", "xxx-1.algolianet.com", "xxx-3.algolianet.com"],
 @search_timeout=5,
 @send_timeout=30,
 @ssl=true,
 @ssl_version=nil>
```

Any help would be great.

Let me know if required more details.

Thanks

Eric

**Comment by wee007** [comment]
Resolved - http://stackoverflow.com/questions/39884959/algolia-search-unable-to-reindex-locally

**Comment by redox** [comment]
👍 @wee007 ; that makes sense.
